### ISSUE TITLE
Issues with 'sort groups' and recurrence '1d 1w 1m 1y'

### ISSUE THREAD

**Issue by marioseixas** [im-n1/eagle#1]
Hello!

Awesome software, please keep up the good work, I will use this for life.

I've already tried checkvist, ultralist, taskwarrior, tasklite, etc and yours it's the most useful and I'm very grateful to you.

I only have issues with the sort feature that doesn't work for me. I tried several forms, and the one that doesn't return a error is 'e --sort groups', but also return nothing.

The error is: eagle: error: argument --sort: invalid choice: '{groups}' (choose from 'groups')

Also the recurring shows:

Today:
	20. test one week (1w)
	21. test one day (1d)
	22. test one month (1m)
	23. test one year (1y)

instead of (every week), etc

Can you help? Thanks

**Comment by marioseixas** [comment]
Case closed, I figured it out, thanks
![alias](https://user-images.githubusercontent.com/9296780/83970391-e4d10900-a8ab-11ea-955d-1b0937b908dd.png)

**Comment by im-n1** [comment]
Sorry for the delay - I haven't got the notification. I will look at i asap.

**Comment by im-n1** [comment]
Thank you for your words.

Also if you have a specific proposal, feel free to open up new issue.

Closing this for now.
